### ISSUE TITLE
[CPU Scheduler/Cacule] Laggy under high-extreme load/high CPU usage

### ISSUE THREAD

**Issue by m0lese** [m0lese/Linux-Phaco#24]
CPU Scheduler: Cacule
CPU Scheduler Version: 5.12-r2
Kernel Configuration file: [.config](https://raw.githubusercontent.com/m0lese/Linux-Misc/prime/config)

### TODO
  - [x] Confirm
  - [ ] Reproduce
  - [x] Verify
  - [ ] Debug
  - [ ] Extend the list if necessary
  
### Note
HZ_2000 is more laggy than HZ_1000.

**Comment by m0lese** [comment]
Hey @hamadmarri!

**Q**. What kind of load that causes this issue?
**A**. Mostly when compiling software; like python3.10-alpha, 6.0.0-Phaco-gdffc37bec677, playing HD audio on youtube with firefox and doing running other lightweight-mid-weight applications.

**Q**. Does CFS without cacule had the same issue under the same load?
**A**. No. Also tested MuQSS CPU Scheduler. No issues so far on either of them.

**Q**. Could you please confirm if autogroup is not disabled at run time?
**A**. Sure.
```bash
doas sysctl kernel | grep autogr
kernel.sched_autogroup_enabled = 0
```


Going to try **CONFIG_NO_HZ_IDLE**. Thank you so much for trying to help me :)

**Comment by m0lese** [comment]
### TODO
- [x] Replace **CONFIG_NO_HZ_IDLE** with **CONFIG_HZ_PERIODIC**
- [ ] Try/Test **CONFIG_NO_HZ_IDLE**

**Comment by hamadmarri** [comment]
```
doas sysctl kernel | grep autogr
kernel.sched_autogroup_enabled = 0
```

autogroup should be enabled
it is the main reason for this issue
I am not sure what task disabled it, maybe you are using ananicy?

please try with enabled autogroup 

run this command
`sudo sysctl kernel.sched_autogroup_enabled=1`

**Comment by m0lese** [comment]
Yes, I've ananicy process enabled and running as a systemd service.

autogroup has been enabled.
```bash
~ doas sysctl kernel.sched_autogroup_enabled=1
kernel.sched_autogroup_enabled = 1

~ doas sysctl kernel | grep autogr
kernel.sched_autogroup_enabled = 1
```

**Comment by m0lese** [comment]
Hi @hamadmarri!

The issue is still present even after enabling autogroup. Executed `doas sysctl kernel.sched_autogroup_enabled=1` then tested 2 times, rebooted the system, tried again and confirmed. Note `autogroup` was enabled at runtime during the tests.

**Comment by m0lese** [comment]
Tried **CONFIG_NO_HZ_IDLE** instead of **CONFIG_HZ_PERIODIC**. The issue is still present!

**Comment by hamadmarri** [comment]
> ananicy

AFAIK, ananicy keeps disabling autogroup. It does periodic checks every 10s IIRC. Try without ananicy or disable it.
And btw, I have negative opinion towards ananicy. I don't like it. If you need to smooth down some tasks, try a simple solution like this https://github.com/hamadmarri/ntn it doesn't add any overhead nor manipulating cgroups.

**Comment by hamadmarri** [comment]
I am sure it is not related to CONFIG_NO_HZ_IDLE nor CONFIG_HZ_PERIODIC. It is ananicy

**Comment by m0lese** [comment]
> The issue is still present even after enabling autogroup. Executed doas sysctl kernel.sched_autogroup_enabled=1 then tested 2 times, rebooted the system, tested again and confirmed. Note autogroup was enabled at runtime during the tests.

Those tests were performed after uninstalling ananicy completely.

**Comment by hamadmarri** [comment]
You might give cacule+rdb a try. 2000HZ is not a default nor a recommendation for cacule. It is just an option for who would like to test. I suggest 500HZ or similar HZ as CFS you tested.

Thank you

**Comment by m0lese** [comment]
Gotcha!

**Comment by m0lese** [comment]
Relevant: https://github.com/hamadmarri/cacule-cpu-scheduler/issues/47
