### ISSUE TITLE
Kernel does not boot (since  01ded22)

### ISSUE THREAD

**Issue by m0lese** [m0lese/Linux-Phaco#32]
# Todo
  - **CHECK:**
    - [x] d72a0c76ad868de8f6fba251b9b15f82782f9484
    - [x] 94281250ac5dbfbbf99d094b3b9a22d21a8db58b
    - [x] 9236ad37b5635a4f6137e992fa8b9a33df863d4b
    - [x] a6aeb3212679c9e79767f9a155cfd4226d8cc8b6

Culprit: 9236ad37b5635a4f6137e992fa8b9a33df863d4b

**Comment by m0lese** [comment]
fixed in 1bf8c819294634c75975ec42e8d983d924c98602
